### PR TITLE
Update the Rust book's details.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ltratt** [comment]
Just realised I should have updated the ID for this. Hang on a sec.

**Comment by ltratt** [comment]
OK, try that.

Note, we *do* break backwards compatibility by changing the ID, but the old ID was dumb (and I'm about 98% certain I'm responsible for that dumbness).

**Comment by vext01** [comment]
I think there's an `edition` field which you could utilise.

**Comment by ltratt** [comment]
It seems that the print book doesn't technically have editions (not yet)...

**Comment by vext01** [comment]
Eh. That's annoying. IIRC the printed one is the second edition of the online one.

Up to you if you call that 2nd edition or not.

Everything else is fine.

**Comment by vext01** [comment]
[do you need to grep the softdev and paper repos looking for broken refs?]

**Comment by ltratt** [comment]
It's only in one (not very important) non-paper part of the repo.

I don't think we can call this the 2nd edition, since the publisher site doesn't designate it that way. I suggest I squash and then we merge.

**Comment by vext01** [comment]
Go ahead.

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
