### PR TITLE
Add minimal Docker file to install TeXLive.

### PR DESCRIPTION
**Pull request by ltratt**
I expect I'll need a few goes to work out the right subset of TeXLive packages to install...

### CODE REVIEW

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
@vext01 Any idea why the last two buildbot invocations don't seem to have picked up https://github.com/softdevteam/softdevbib/pull/76/commits/33aa2fe114807f3b72d0e1263fd6ecfc1825bce0 ?

**Comment by vext01** [comment]
```
+ ls .buildbot_dockerfile_*
ls: cannot access '.buildbot_dockerfile_*': No such file or directory
...
+ ci_dockerfiles=.buildbot_dockerfile_default
```

It's still using the default image because ` .buildbot_docker_debian` should be `.buildbot_dockerfile_debian`.

[I don't think you need the python3 symlink btw]

**Comment by ltratt** [comment]
I'm an idiot!

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
OK to squash?

**Comment by vext01** [comment]
LGTM. Please squash.

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
