### PR TITLE
Homogenise name.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ltratt** [comment]
Hang on with this one.

**Comment by ltratt** [comment]
OK, the second commit fixes the fact that having an author "Intel Corporation" means that the citation shows up as "Corporation" in the text!

**Comment by vext01** [comment]
squasharoo?

**Comment by ltratt** [comment]
They're technically two different actions, so I'm OK leaving them as-is.

**Comment by vext01** [comment]
OK

**Pull request merged**
