### PR TITLE
Add a couple of CHERI papers.

### PR DESCRIPTION
**Pull request by ltratt**
@drpdr This is our bibliography repo. To review things here, please check a) the citations below are correct w.r.t. the original papers b) the style of the citations matches that of others in the repository. If/when you're happy, you can run bors, which will also run some basic sanity checks to make sure we haven't done anything very obviously silly in these BibTeX records.

### CODE REVIEW

**Comment by ltratt** [comment]
bors try

**Review by drpdr — CHANGES_REQUESTED** [review]
What about this [one](https://www.cl.cam.ac.uk/techreports/UCAM-CL-TR-951.html)? It's long but it's required to understand things in depth. Simple permissions are covered by *TR-947*, but data compartments are not.

**Comment by ltratt** [comment]
We don't worry about bibliography PRs including *all* papers though, just the ones the current author thinks they need. Your suggestion would make an excellent next PR, however :)

**Comment by drpdr** [comment]
> We don't worry about bibliography PRs including _all_ papers though, just the ones the current author thinks they need. Your suggestion would make an excellent next PR, however :)

OK, then. I didn't know :)

**Comment by drpdr** [comment]
bors try

**Pull request merged**
