### PR TITLE
Add the CHERIvoke paper.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ltratt** [comment]
Can you try again? I'm not sure if I've allowed you or not!

**Comment by ltratt** [comment]
OK, I *think* I've found where you're not listed... but I don't know why you're not listed there! I'm trying to find out more...

**Comment by ltratt** [comment]
Aha, I think I've done it. Before we do a merge, are you OK for me to force push an update that removes the merge commit?

**Comment by 0152la** [comment]
Yes, that would be for the best.

**Comment by ltratt** [comment]
OK, the merge commit has gone and I *think* bors should now let you do things. If you're happy, please try `r+`ing it.

**Pull request merged**
