### PR TITLE
Add an entry for the LMCS '15 paper.

### PR DESCRIPTION
**Pull request by ltratt**
Edd: I think this can also become a `.bib` file on the website?

### CODE REVIEW

**Comment by vext01** [comment]
Do we want to use double quotes or curly braces? Looks like the majority of the file uses curly braces, but the previous entry uses quotes.

(Will add an entry to the website tomorrow.)

**Comment by ltratt** [comment]
I don't feel strongly either way. Do you have a preference?

**Comment by vext01** [comment]
I always use curly braces myself.

**Comment by ltratt** [comment]
See if that works for you.

**Comment by vext01** [comment]
Works for me

**Comment by ltratt** [comment]
OK, here's a squashed version suitable for merging.

**Comment by vext01** [comment]
@ltratt following up on the bibtex file for the website, seems the paper already has one.

**Comment by ltratt** [comment]
Oh yeah, doh. Sorry!

**Pull request merged**
