### PR TITLE
Add bors/buildbot support.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by vext01** [comment]
bors ping

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
```
/bin/sh: 1: python3.5: not found
```

Ah the joys of python.

`python3` or `python3.7` will work on bencher13.

**Comment by ltratt** [comment]
`python3` makes most sense so that we don't hit this again.

**Comment by ltratt** [comment]
bors r-

I'm not sure why bors says "cancelled", so it might be worth trying again.

**Pull request merged**
